//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIChessDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIChessDatabase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bbishop {
            get {
                object obj = ResourceManager.GetObject("bbishop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bking {
            get {
                object obj = ResourceManager.GetObject("bking", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bknight {
            get {
                object obj = ResourceManager.GetObject("bknight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Board {
            get {
                object obj = ResourceManager.GetObject("Board", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bpawn {
            get {
                object obj = ResourceManager.GetObject("bpawn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bqueen {
            get {
                object obj = ResourceManager.GetObject("bqueen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] brook {
            get {
                object obj = ResourceManager.GetObject("brook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bwbishop {
            get {
                object obj = ResourceManager.GetObject("bwbishop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bwking {
            get {
                object obj = ResourceManager.GetObject("bwking", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bwknight {
            get {
                object obj = ResourceManager.GetObject("bwknight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bwpawn {
            get {
                object obj = ResourceManager.GetObject("bwpawn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bwqueen {
            get {
                object obj = ResourceManager.GetObject("bwqueen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] bwrook {
            get {
                object obj = ResourceManager.GetObject("bwrook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MATCH.
        /// </summary>
        internal static string CAT_MATCH {
            get {
                return ResourceManager.GetString("CAT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOVE.
        /// </summary>
        internal static string CAT_MOVE {
            get {
                return ResourceManager.GetString("CAT_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChessPiecesArray {
            get {
                object obj = ResourceManager.GetObject("ChessPiecesArray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ChessPiecesArraySmall {
            get {
                object obj = ResourceManager.GetObject("ChessPiecesArraySmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MATCH.
        /// </summary>
        internal static string FCAT_MATCH {
            get {
                return ResourceManager.GetString("FCAT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOVE.
        /// </summary>
        internal static string FCAT_MOVE {
            get {
                return ResourceManager.GetString("FCAT_MOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a documents.json.
        /// </summary>
        internal static string FILE_DocumentRepository {
            get {
                return ResourceManager.GetString("FILE_DocumentRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FunctionCalling {
            get {
                object obj = ResourceManager.GetObject("FunctionCalling", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_CodeInterpreter {
            get {
                object obj = ResourceManager.GetObject("ICO_CodeInterpreter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon ICO_Console {
            get {
                object obj = ResourceManager.GetObject("ICO_Console", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ICO_FileSearch {
            get {
                object obj = ResourceManager.GetObject("ICO_FileSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon ICO_WebSearch {
            get {
                object obj = ResourceManager.GetObject("ICO_WebSearch", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BOARDWINDOW.
        /// </summary>
        internal static string ID_BOARDWINDOW {
            get {
                return ResourceManager.GetString("ID_BOARDWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DATABASEWINDOW.
        /// </summary>
        internal static string ID_DATABASEWINDOW {
            get {
                return ResourceManager.GetString("ID_DATABASEWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FILTERDITORWINDOW.
        /// </summary>
        internal static string ID_FILTEREDITORWINDOW {
            get {
                return ResourceManager.GetString("ID_FILTEREDITORWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MATCHWINDOW.
        /// </summary>
        internal static string ID_MATCHWINDOW {
            get {
                return ResourceManager.GetString("ID_MATCHWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOVEWINDOW.
        /// </summary>
        internal static string ID_MOVEDBWINDOW {
            get {
                return ResourceManager.GetString("ID_MOVEDBWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PGNWINDOW.
        /// </summary>
        internal static string ID_PGNWINDOW {
            get {
                return ResourceManager.GetString("ID_PGNWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAYWINDOW.
        /// </summary>
        internal static string ID_PLAYWINDOW {
            get {
                return ResourceManager.GetString("ID_PLAYWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QUERYWINDOW.
        /// </summary>
        internal static string ID_QUERYWINDOW {
            get {
                return ResourceManager.GetString("ID_QUERYWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rnbqkbnrpppppppp00000000000000000000000000000000PPPPPPPPRNBQKBNR.
        /// </summary>
        internal static string INITIAL_BOARD {
            get {
                return ResourceManager.GetString("INITIAL_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a rnbqkbnrpppppppp00000000000000000000000000000000PPPPPPPPRNBQKBNR.
        /// </summary>
        internal static string INITIAL_BOARD_STANDARD {
            get {
                return ResourceManager.GetString("INITIAL_BOARD_STANDARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Black.
        /// </summary>
        internal static string KEY_BLACK {
            get {
                return ResourceManager.GetString("KEY_BLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string KEY_DATE {
            get {
                return ResourceManager.GetString("KEY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        internal static string KEY_DATE1 {
            get {
                return ResourceManager.GetString("KEY_DATE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Event.
        /// </summary>
        internal static string KEY_EVENT {
            get {
                return ResourceManager.GetString("KEY_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Result.
        /// </summary>
        internal static string KEY_RESULT {
            get {
                return ResourceManager.GetString("KEY_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Round.
        /// </summary>
        internal static string KEY_ROUND {
            get {
                return ResourceManager.GetString("KEY_ROUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Site.
        /// </summary>
        internal static string KEY_SITE {
            get {
                return ResourceManager.GetString("KEY_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a White.
        /// </summary>
        internal static string KEY_WHITE {
            get {
                return ResourceManager.GetString("KEY_WHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a *null*.
        /// </summary>
        internal static string NULL_VALUE {
            get {
                return ResourceManager.GetString("NULL_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WINDOWSDESKTOP.
        /// </summary>
        internal static string PLATFORM_WINDOWSDESK {
            get {
                return ResourceManager.GetString("PLATFORM_WINDOWSDESK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a appFunctions.
        /// </summary>
        internal static string SETTING_appFunctions {
            get {
                return ResourceManager.GetString("SETTING_appFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConfigPath.
        /// </summary>
        internal static string SETTING_ConfigPath {
            get {
                return ResourceManager.GetString("SETTING_ConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConsoleLog.
        /// </summary>
        internal static string SETTING_ConsoleLog {
            get {
                return ResourceManager.GetString("SETTING_ConsoleLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CredentialStore.
        /// </summary>
        internal static string SETTING_CredentialStore {
            get {
                return ResourceManager.GetString("SETTING_CredentialStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CredentialStoreKeyData.
        /// </summary>
        internal static string SETTING_CredentialStoreKeyData {
            get {
                return ResourceManager.GetString("SETTING_CredentialStoreKeyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dataPath.
        /// </summary>
        internal static string SETTING_dataPath {
            get {
                return ResourceManager.GetString("SETTING_dataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbconnections.
        /// </summary>
        internal static string SETTING_dbconnections {
            get {
                return ResourceManager.GetString("SETTING_dbconnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbconstring.
        /// </summary>
        internal static string SETTING_dbconstring {
            get {
                return ResourceManager.GetString("SETTING_dbconstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a defaultPlay.
        /// </summary>
        internal static string SETTING_defaultPlay {
            get {
                return ResourceManager.GetString("SETTING_defaultPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a filesAPI.
        /// </summary>
        internal static string SETTING_filesAPI {
            get {
                return ResourceManager.GetString("SETTING_filesAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FunctionCallLog.
        /// </summary>
        internal static string SETTING_FunctionCallLog {
            get {
                return ResourceManager.GetString("SETTING_FunctionCallLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        internal static string SETTING_Language {
            get {
                return ResourceManager.GetString("SETTING_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LogPathBase.
        /// </summary>
        internal static string SETTING_LogPathBase {
            get {
                return ResourceManager.GetString("SETTING_LogPathBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nsQueries.
        /// </summary>
        internal static string SETTING_nsQueries {
            get {
                return ResourceManager.GetString("SETTING_nsQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PGNdir.
        /// </summary>
        internal static string SETTING_PGNdir {
            get {
                return ResourceManager.GetString("SETTING_PGNdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a playCollection.
        /// </summary>
        internal static string SETTING_playCollection {
            get {
                return ResourceManager.GetString("SETTING_playCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a supportedLanguages.
        /// </summary>
        internal static string SETTING_supportedLanguages {
            get {
                return ResourceManager.GetString("SETTING_supportedLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tokenUsageLog.
        /// </summary>
        internal static string SETTING_tokenUsageLog {
            get {
                return ResourceManager.GetString("SETTING_tokenUsageLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a updateConfiguration.
        /// </summary>
        internal static string SETTING_updateConfiguration {
            get {
                return ResourceManager.GetString("SETTING_updateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Event .
        /// </summary>
        internal static string TXT_PGNSTART {
            get {
                return ResourceManager.GetString("TXT_PGNSTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MKW.
        /// </summary>
        internal static string TYPE_MATCHKEYWORD {
            get {
                return ResourceManager.GetString("TYPE_MATCHKEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MST.
        /// </summary>
        internal static string TYPE_MATCHSTATISTIC {
            get {
                return ResourceManager.GetString("TYPE_MATCHSTATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PST.
        /// </summary>
        internal static string TYPE_POSSTATISTIC {
            get {
                return ResourceManager.GetString("TYPE_POSSTATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] wbishop {
            get {
                object obj = ResourceManager.GetObject("wbishop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] wking {
            get {
                object obj = ResourceManager.GetObject("wking", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] wknight {
            get {
                object obj = ResourceManager.GetObject("wknight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] wpawn {
            get {
                object obj = ResourceManager.GetObject("wpawn", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] wqueen {
            get {
                object obj = ResourceManager.GetObject("wqueen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Byte[].
        /// </summary>
        internal static byte[] wrook {
            get {
                object obj = ResourceManager.GetObject("wrook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a black.
        /// </summary>
        internal static string XML_BLACK {
            get {
                return ResourceManager.GetString("XML_BLACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a blackorwhite.
        /// </summary>
        internal static string XML_BLACKORWHITE {
            get {
                return ResourceManager.GetString("XML_BLACKORWHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a board.
        /// </summary>
        internal static string XML_BOARD {
            get {
                return ResourceManager.GetString("XML_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a captures.
        /// </summary>
        internal static string XML_CAPTURES {
            get {
                return ResourceManager.GetString("XML_CAPTURES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a categories.
        /// </summary>
        internal static string XML_CATEGORIES {
            get {
                return ResourceManager.GetString("XML_CATEGORIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a customboard.
        /// </summary>
        internal static string XML_CBOARD {
            get {
                return ResourceManager.GetString("XML_CBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a color.
        /// </summary>
        internal static string XML_COLOR {
            get {
                return ResourceManager.GetString("XML_COLOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a filtercontainer.
        /// </summary>
        internal static string XML_CONTAINER {
            get {
                return ResourceManager.GetString("XML_CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a containers.
        /// </summary>
        internal static string XML_CONTAINERS {
            get {
                return ResourceManager.GetString("XML_CONTAINERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a date.
        /// </summary>
        internal static string XML_DATE {
            get {
                return ResourceManager.GetString("XML_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a description.
        /// </summary>
        internal static string XML_DESCRIPTION {
            get {
                return ResourceManager.GetString("XML_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a filterelement.
        /// </summary>
        internal static string XML_ELEMENT {
            get {
                return ResourceManager.GetString("XML_ELEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a elements.
        /// </summary>
        internal static string XML_ELEMENTS {
            get {
                return ResourceManager.GetString("XML_ELEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a event.
        /// </summary>
        internal static string XML_EVENT {
            get {
                return ResourceManager.GetString("XML_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a movecount.
        /// </summary>
        internal static string XML_FMOVCOUNT {
            get {
                return ResourceManager.GetString("XML_FMOVCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fullmoves.
        /// </summary>
        internal static string XML_FMOVES {
            get {
                return ResourceManager.GetString("XML_FMOVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a from.
        /// </summary>
        internal static string XML_FROM {
            get {
                return ResourceManager.GetString("XML_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a join.
        /// </summary>
        internal static string XML_JOIN {
            get {
                return ResourceManager.GetString("XML_JOIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a maxcount.
        /// </summary>
        internal static string XML_MAXCOUNT {
            get {
                return ResourceManager.GetString("XML_MAXCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a keyword.
        /// </summary>
        internal static string XML_MCFKEYWORD {
            get {
                return ResourceManager.GetString("XML_MCFKEYWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a matchkeywordfilter.
        /// </summary>
        internal static string XML_MFC {
            get {
                return ResourceManager.GetString("XML_MFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a matchinfofilter.
        /// </summary>
        internal static string XML_MIF {
            get {
                return ResourceManager.GetString("XML_MIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a description.
        /// </summary>
        internal static string XML_MIFDESC {
            get {
                return ResourceManager.GetString("XML_MIFDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a mincount.
        /// </summary>
        internal static string XML_MINCOUNT {
            get {
                return ResourceManager.GetString("XML_MINCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a plycount.
        /// </summary>
        internal static string XML_MOVCOUNT {
            get {
                return ResourceManager.GetString("XML_MOVCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a moves.
        /// </summary>
        internal static string XML_MOVES {
            get {
                return ResourceManager.GetString("XML_MOVES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a moveplayerfilter.
        /// </summary>
        internal static string XML_MPF {
            get {
                return ResourceManager.GetString("XML_MPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a movepositionfilter.
        /// </summary>
        internal static string XML_MPOSF {
            get {
                return ResourceManager.GetString("XML_MPOSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a movepiecefilter.
        /// </summary>
        internal static string XML_MPZF {
            get {
                return ResourceManager.GetString("XML_MPZF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a matchstatisticsfilter.
        /// </summary>
        internal static string XML_MSF {
            get {
                return ResourceManager.GetString("XML_MSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a movesquarefilter.
        /// </summary>
        internal static string XML_MSQF {
            get {
                return ResourceManager.GetString("XML_MSQF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a name.
        /// </summary>
        internal static string XML_NAME {
            get {
                return ResourceManager.GetString("XML_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a operator.
        /// </summary>
        internal static string XML_OPERATOR {
            get {
                return ResourceManager.GetString("XML_OPERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a piece.
        /// </summary>
        internal static string XML_PIECE {
            get {
                return ResourceManager.GetString("XML_PIECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a pieces.
        /// </summary>
        internal static string XML_PIECES {
            get {
                return ResourceManager.GetString("XML_PIECES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a promoted.
        /// </summary>
        internal static string XML_PROMOTED {
            get {
                return ResourceManager.GetString("XML_PROMOTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a posstatisticsfilter.
        /// </summary>
        internal static string XML_PSF {
            get {
                return ResourceManager.GetString("XML_PSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a piecescountfilter.
        /// </summary>
        internal static string XML_PZCF {
            get {
                return ResourceManager.GetString("XML_PZCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a regex.
        /// </summary>
        internal static string XML_REGEX {
            get {
                return ResourceManager.GetString("XML_REGEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a result.
        /// </summary>
        internal static string XML_RESULT {
            get {
                return ResourceManager.GetString("XML_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a filterdatabase.
        /// </summary>
        internal static string XML_ROOT {
            get {
                return ResourceManager.GetString("XML_ROOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a selection.
        /// </summary>
        internal static string XML_SELECTION {
            get {
                return ResourceManager.GetString("XML_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a to.
        /// </summary>
        internal static string XML_TO {
            get {
                return ResourceManager.GetString("XML_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a realtype.
        /// </summary>
        internal static string XML_TYPE {
            get {
                return ResourceManager.GetString("XML_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a uid.
        /// </summary>
        internal static string XML_UID {
            get {
                return ResourceManager.GetString("XML_UID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a value.
        /// </summary>
        internal static string XML_VALUE {
            get {
                return ResourceManager.GetString("XML_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a white.
        /// </summary>
        internal static string XML_WHITE {
            get {
                return ResourceManager.GetString("XML_WHITE", resourceCulture);
            }
        }
    }
}
