//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalCommonEntities.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlobalCommonEntities.Properties.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azure Key Vault.
        /// </summary>
        internal static string BTTL_AzureKey {
            get {
                return ResourceManager.GetString("BTTL_AzureKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The unique identifier you assign to a secret when storing it in Azure Key Vault..
        /// </summary>
        internal static string DESC_AzureKeyVaultStoreKey_SecretName {
            get {
                return ResourceManager.GetString("DESC_AzureKeyVaultStoreKey_SecretName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The unique HTTPS endpoint of an Azure Key Vault instance (e.g., https://myvault.vault.azure.net/)..
        /// </summary>
        internal static string DESC_AzureKeyVaultStoreKey_VaultUri {
            get {
                return ResourceManager.GetString("DESC_AzureKeyVaultStoreKey_VaultUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azure Key Vault.
        /// </summary>
        internal static string NAME_AzureKeyVaultStore {
            get {
                return ResourceManager.GetString("NAME_AzureKeyVaultStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Secret Name.
        /// </summary>
        internal static string NAME_AzureKeyVaultStoreKey_SecretName {
            get {
                return ResourceManager.GetString("NAME_AzureKeyVaultStoreKey_SecretName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vault Uri.
        /// </summary>
        internal static string NAME_AzureKeyVaultStoreKey_VaultUri {
            get {
                return ResourceManager.GetString("NAME_AzureKeyVaultStoreKey_VaultUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Application Configuration File.
        /// </summary>
        internal static string NAME_ConfigFileCredentialStore {
            get {
                return ResourceManager.GetString("NAME_ConfigFileCredentialStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Environment Variable.
        /// </summary>
        internal static string NAME_EnvironmentVariable {
            get {
                return ResourceManager.GetString("NAME_EnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Windows Credential Manager.
        /// </summary>
        internal static string NAME_WindowsCredentialManager {
            get {
                return ResourceManager.GetString("NAME_WindowsCredentialManager", resourceCulture);
            }
        }
    }
}
