USE [master]
GO
sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
sp_configure 'clr enabled', 1;
GO
RECONFIGURE;
GO
/****** Object:  Database [CHESSPOSDB]    Script Date: 25/03/2020 16:26:31 ******/
CREATE DATABASE [CHESSPOSDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CHESSPOSDB', FILENAME = N'F:\SQL Server 2016\MSSQL13.SQLSRV2016\MSSQL\DATA\CHESSPOSDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CHESSPOSDB_log', FILENAME = N'F:\SQL Server 2016\MSSQL13.SQLSRV2016\MSSQL\DATA\CHESSPOSDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CHESSPOSDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CHESSPOSDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CHESSPOSDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CHESSPOSDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CHESSPOSDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CHESSPOSDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CHESSPOSDB] SET  MULTI_USER 
GO

ALTER DATABASE [CHESSPOSDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CHESSPOSDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CHESSPOSDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CHESSPOSDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CHESSPOSDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CHESSPOSDB] SET QUERY_STORE = OFF
GO

USE [CHESSPOSDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CHESSPOSDB] SET  READ_WRITE 
GO

