//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopControls.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIElements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIElements() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopControls.Properties.UIElements", typeof(UIElements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check this button to select objects to add to the collection.
        /// </summary>
        internal static string ObjectSelector_bAddMode_Description {
            get {
                return ResourceManager.GetString("ObjectSelector_bAddMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Mode Button.
        /// </summary>
        internal static string ObjectSelector_bAddMode_Name {
            get {
                return ResourceManager.GetString("ObjectSelector_bAddMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check this button to remove objects from the collection.
        /// </summary>
        internal static string ObjectSelector_bDeleteMode_Description {
            get {
                return ResourceManager.GetString("ObjectSelector_bDeleteMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Mode Button.
        /// </summary>
        internal static string ObjectSelector_bDeleteMode_Name {
            get {
                return ResourceManager.GetString("ObjectSelector_bDeleteMode_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceed adding or removing the selected objects.
        /// </summary>
        internal static string ObjectSelector_bProceed_Description {
            get {
                return ResourceManager.GetString("ObjectSelector_bProceed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceed Button.
        /// </summary>
        internal static string ObjectSelector_bProceed_Name {
            get {
                return ResourceManager.GetString("ObjectSelector_bProceed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh objects in the selection list.
        /// </summary>
        internal static string ObjectSelector_bRefresh_Description {
            get {
                return ResourceManager.GetString("ObjectSelector_bRefresh_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh Button.
        /// </summary>
        internal static string ObjectSelector_bRefresh_Name {
            get {
                return ResourceManager.GetString("ObjectSelector_bRefresh_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove the container object as well as all its content.
        /// </summary>
        internal static string ObjectSelector_bRemoveObject_Description {
            get {
                return ResourceManager.GetString("ObjectSelector_bRemoveObject_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Container Button.
        /// </summary>
        internal static string ObjectSelector_bRemoveObject_Name {
            get {
                return ResourceManager.GetString("ObjectSelector_bRemoveObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List with all the objects that can be added or removed from the collection.
        /// </summary>
        internal static string ObjectSelector_lvSelection_Description {
            get {
                return ResourceManager.GetString("ObjectSelector_lvSelection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selection List.
        /// </summary>
        internal static string ObjectSelector_lvSelection_Name {
            get {
                return ResourceManager.GetString("ObjectSelector_lvSelection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toolbar with command buttons to manage the object selection lists.
        /// </summary>
        internal static string ObjectSelector_toolbar_Description {
            get {
                return ResourceManager.GetString("ObjectSelector_toolbar_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object Selector ToolBar.
        /// </summary>
        internal static string ObjectSelector_toolbar_Name {
            get {
                return ResourceManager.GetString("ObjectSelector_toolbar_Name", resourceCulture);
            }
        }
    }
}
