//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopControls.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DesktopControls.Properties.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        internal static string BTN_Apply {
            get {
                return ResourceManager.GetString("BTN_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string BTN_Cancel {
            get {
                return ResourceManager.GetString("BTN_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string BTN_OK {
            get {
                return ResourceManager.GetString("BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove.
        /// </summary>
        internal static string BTN_Remove {
            get {
                return ResourceManager.GetString("BTN_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        internal static string CAP_Error {
            get {
                return ResourceManager.GetString("CAP_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TreeView showing .
        /// </summary>
        internal static string CAP_TreeNode {
            get {
                return ResourceManager.GetString("CAP_TreeNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waning.
        /// </summary>
        internal static string CAP_Warning {
            get {
                return ResourceManager.GetString("CAP_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uncheck to nullate value.
        /// </summary>
        internal static string DESC_NullCheckBox {
            get {
                return ResourceManager.GetString("DESC_NullCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editor type not valid.
        /// </summary>
        internal static string ERR_BadEditorType {
            get {
                return ResourceManager.GetString("ERR_BadEditorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instance type not valid.
        /// </summary>
        internal static string ERR_BadInstanceType {
            get {
                return ResourceManager.GetString("ERR_BadInstanceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Property type not valid.
        /// </summary>
        internal static string ERR_BadPropertyType {
            get {
                return ResourceManager.GetString("ERR_BadPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IIndexedPropertyValueManager needed.
        /// </summary>
        internal static string ERR_IndexedProperty {
            get {
                return ResourceManager.GetString("ERR_IndexedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid operation for multiple editors.
        /// </summary>
        internal static string ERR_InvalidMultipleOperation {
            get {
                return ResourceManager.GetString("ERR_InvalidMultipleOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No control with Dock=Fill found to capture..
        /// </summary>
        internal static string ERR_NOFILLCONTROL {
            get {
                return ResourceManager.GetString("ERR_NOFILLCONTROL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IPropertyConfigurationProvider needed.
        /// </summary>
        internal static string ERR_PropertyConfiguration {
            get {
                return ResourceManager.GetString("ERR_PropertyConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Some required fields are missing..
        /// </summary>
        internal static string ERR_RequiredData {
            get {
                return ResourceManager.GetString("ERR_RequiredData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown command method.
        /// </summary>
        internal static string ERR_UnknownMethod {
            get {
                return ResourceManager.GetString("ERR_UnknownMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unknown property name.
        /// </summary>
        internal static string ERR_UnknownProperty {
            get {
                return ResourceManager.GetString("ERR_UnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read only properties cannot be expandable.
        /// </summary>
        internal static string ERROR_NonExpandable {
            get {
                return ResourceManager.GetString("ERROR_NonExpandable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Object Selector Dialog Box.
        /// </summary>
        internal static string FNAME_ObjectSelector {
            get {
                return ResourceManager.GetString("FNAME_ObjectSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Files.
        /// </summary>
        internal static string LAB_FIles {
            get {
                return ResourceManager.GetString("LAB_FIles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This action will remove {0}. Do you want to proceed anyway?.
        /// </summary>
        internal static string MSG_RemovePropertyObject {
            get {
                return ResourceManager.GetString("MSG_RemovePropertyObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Command.
        /// </summary>
        internal static string NAME_command {
            get {
                return ResourceManager.GetString("NAME_command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desktop Controls Interactor.
        /// </summary>
        internal static string NAME_ControlInteractor {
            get {
                return ResourceManager.GetString("NAME_ControlInteractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default Input Editor Factory.
        /// </summary>
        internal static string NAME_InputEditorFactory {
            get {
                return ResourceManager.GetString("NAME_InputEditorFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has Value.
        /// </summary>
        internal static string NAME_NullCheckBox {
            get {
                return ResourceManager.GetString("NAME_NullCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desktop Relevant Control Collector.
        /// </summary>
        internal static string NAME_RelevantControlCollector {
            get {
                return ResourceManager.GetString("NAME_RelevantControlCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  (header).
        /// </summary>
        internal static string SFX_HEADER {
            get {
                return ResourceManager.GetString("SFX_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Content Mode.
        /// </summary>
        internal static string TTP_AddMode {
            get {
                return ResourceManager.GetString("TTP_AddMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proceed to update the selection.
        /// </summary>
        internal static string TTP_Proceed {
            get {
                return ResourceManager.GetString("TTP_Proceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh Listing.
        /// </summary>
        internal static string TTP_Refresh {
            get {
                return ResourceManager.GetString("TTP_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Container Object.
        /// </summary>
        internal static string TTP_RemoveContainer {
            get {
                return ResourceManager.GetString("TTP_RemoveContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Content Mode.
        /// </summary>
        internal static string TTP_RemoveMode {
            get {
                return ResourceManager.GetString("TTP_RemoveMode", resourceCulture);
            }
        }
    }
}
