//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 562cc292442b4f26bb064d7ddfc31479.
        /// </summary>
        public static string APP_3337A0107B324B33B4699C1A529F3ED0_CONNQ {
            get {
                return ResourceManager.GetString("APP_3337A0107B324B33B4699C1A529F3ED0_CONNQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 9b9a55a3d848445ba77065c359dc90e8.
        /// </summary>
        public static string APP_3337A0107B324B33B4699C1A529F3ED0_PARAMQ {
            get {
                return ResourceManager.GetString("APP_3337A0107B324B33B4699C1A529F3ED0_PARAMQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a cod_user.
        /// </summary>
        public static string CAP_LOGUserCode {
            get {
                return ResourceManager.GetString("CAP_LOGUserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a username.
        /// </summary>
        public static string CAP_LOGUserName {
            get {
                return ResourceManager.GetString("CAP_LOGUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ow_friendlydescription.
        /// </summary>
        public static string CAP_OWFriendlyDescription {
            get {
                return ResourceManager.GetString("CAP_OWFriendlyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ow_friendlyname.
        /// </summary>
        public static string CAP_OWFriendlyName {
            get {
                return ResourceManager.GetString("CAP_OWFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ow_value.
        /// </summary>
        public static string CAP_OWKey {
            get {
                return ResourceManager.GetString("CAP_OWKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Assistant.
        /// </summary>
        public static string CATEGORY_ASSISTANT {
            get {
                return ResourceManager.GetString("CATEGORY_ASSISTANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Schema.
        /// </summary>
        public static string CATEGORY_BSCHEMA {
            get {
                return ResourceManager.GetString("CATEGORY_BSCHEMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table.
        /// </summary>
        public static string CATEGORY_BTABLE {
            get {
                return ResourceManager.GetString("CATEGORY_BTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Build Command.
        /// </summary>
        public static string CATEGORY_BUILDCOMMAND {
            get {
                return ResourceManager.GetString("CATEGORY_BUILDCOMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code Formatter.
        /// </summary>
        public static string CATEGORY_CODEFORMATTERS {
            get {
                return ResourceManager.GetString("CATEGORY_CODEFORMATTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a columnEditor.
        /// </summary>
        public static string CATEGORY_COLUMNEDITOR {
            get {
                return ResourceManager.GetString("CATEGORY_COLUMNEDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DataColumn.
        /// </summary>
        public static string CATEGORY_DataColumn {
            get {
                return ResourceManager.GetString("CATEGORY_DataColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Fromatters.
        /// </summary>
        public static string CATEGORY_DATAFORMATTERS {
            get {
                return ResourceManager.GetString("CATEGORY_DATAFORMATTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DataType.
        /// </summary>
        public static string CATEGORY_DATATYPES {
            get {
                return ResourceManager.GetString("CATEGORY_DATATYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database Manager.
        /// </summary>
        public static string CATEGORY_DBMANAGER {
            get {
                return ResourceManager.GetString("CATEGORY_DBMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desktop Application Form.
        /// </summary>
        public static string CATEGORY_FORM {
            get {
                return ResourceManager.GetString("CATEGORY_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Functions.
        /// </summary>
        public static string CATEGORY_FUNCTIONS {
            get {
                return ResourceManager.GetString("CATEGORY_FUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GenericColumn.
        /// </summary>
        public static string CATEGORY_GenericColumn {
            get {
                return ResourceManager.GetString("CATEGORY_GenericColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data Import.
        /// </summary>
        public static string CATEGORY_IMPORTDATA {
            get {
                return ResourceManager.GetString("CATEGORY_IMPORTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IMPORT/EXPORT.
        /// </summary>
        public static string CATEGORY_IMPORTEXPORT {
            get {
                return ResourceManager.GetString("CATEGORY_IMPORTEXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Literals.
        /// </summary>
        public static string CATEGORY_LITERALS {
            get {
                return ResourceManager.GetString("CATEGORY_LITERALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resulting Object.
        /// </summary>
        public static string CATEGORY_OBJRESULT {
            get {
                return ResourceManager.GetString("CATEGORY_OBJRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ORDER BY.
        /// </summary>
        public static string CATEGORY_ORDERBY {
            get {
                return ResourceManager.GetString("CATEGORY_ORDERBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PARAMETERS.
        /// </summary>
        public static string CATEGORY_PARAMETERS {
            get {
                return ResourceManager.GetString("CATEGORY_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query.
        /// </summary>
        public static string CATEGORY_Query {
            get {
                return ResourceManager.GetString("CATEGORY_Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query Clause.
        /// </summary>
        public static string CATEGORY_QUERYCLAUSE {
            get {
                return ResourceManager.GetString("CATEGORY_QUERYCLAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QueryColumn.
        /// </summary>
        public static string CATEGORY_QueryColumn {
            get {
                return ResourceManager.GetString("CATEGORY_QueryColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query Console.
        /// </summary>
        public static string CATEGORY_QUERYCONSOLE {
            get {
                return ResourceManager.GetString("CATEGORY_QUERYCONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Query Link.
        /// </summary>
        public static string CATEGORY_QUERYLINK {
            get {
                return ResourceManager.GetString("CATEGORY_QUERYLINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT.
        /// </summary>
        public static string CATEGORY_SELECT {
            get {
                return ResourceManager.GetString("CATEGORY_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SQL Builder.
        /// </summary>
        public static string CATEGORY_SQLBUILDER {
            get {
                return ResourceManager.GetString("CATEGORY_SQLBUILDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subquery.
        /// </summary>
        public static string CATEGORY_SUBQUERY {
            get {
                return ResourceManager.GetString("CATEGORY_SUBQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ValueListProvider.
        /// </summary>
        public static string CATEGORY_VALUELISTPROVIDERS {
            get {
                return ResourceManager.GetString("CATEGORY_VALUELISTPROVIDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dbProviders.
        /// </summary>
        public static string CONFIG_dbProviders {
            get {
                return ResourceManager.GetString("CONFIG_dbProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dependencyProviders.
        /// </summary>
        public static string CONFIG_dependencyProviders {
            get {
                return ResourceManager.GetString("CONFIG_dependencyProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a resourceManagers.
        /// </summary>
        public static string CONFIG_resourceManagers {
            get {
                return ResourceManager.GetString("CONFIG_resourceManagers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;SerializableQueryConfiguration xmlns=&quot;http://schemas.datacontract.org/2004/07/BaseClassesAndInterfaces.Serialization&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;ColumnUIDs xmlns:a=&quot;http://schemas.datacontract.org/2004/07/BaseClassesAndInterfaces.Application&quot;&gt;&lt;a:SerializableUID&gt;&lt;a:ObjectID&gt;ow_value0&lt;/a:ObjectID&gt;&lt;a:UID&gt;0fdab804cc014abd9f7e4b40bf3756a4&lt;/a:UID&gt;&lt;/a:SerializableUID&gt;&lt;a:SerializableUID&gt;&lt;a:ObjectID&gt;ow_value1&lt;/a:ObjectID&gt;&lt;a:UID&gt;7df5c16a7c384da5aed4fb91293a03c5&lt;/a:UID&gt;&lt;/a:SerializableUID&gt;&lt;a [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string connections {
            get {
                return ResourceManager.GetString("connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a aggregates.
        /// </summary>
        public static string CT_AGGREGATES {
            get {
                return ResourceManager.GetString("CT_AGGREGATES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ambiguousTokens.
        /// </summary>
        public static string CT_AMBIGUOUS {
            get {
                return ResourceManager.GetString("CT_AMBIGUOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a alphanumericOperators.
        /// </summary>
        public static string CT_ANOPERATORS {
            get {
                return ResourceManager.GetString("CT_ANOPERATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BoolConstants.
        /// </summary>
        public static string CT_BOOLCONSTANTS {
            get {
                return ResourceManager.GetString("CT_BOOLCONSTANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a booleanFunctions.
        /// </summary>
        public static string CT_BOOLFUNCTIONS {
            get {
                return ResourceManager.GetString("CT_BOOLFUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a BoolProperties.
        /// </summary>
        public static string CT_BOOLPROPERTIES {
            get {
                return ResourceManager.GetString("CT_BOOLPROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QueryClauses.
        /// </summary>
        public static string CT_BUILDERQUERYCLAUSES {
            get {
                return ResourceManager.GetString("CT_BUILDERQUERYCLAUSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a builderSubqueries.
        /// </summary>
        public static string CT_BUILDERSUBQUERY {
            get {
                return ResourceManager.GetString("CT_BUILDERSUBQUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a builder.
        /// </summary>
        public static string CT_BUILDERTOKENS {
            get {
                return ResourceManager.GetString("CT_BUILDERTOKENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConfigurationCommand.
        /// </summary>
        public static string CT_CONFIGCOMMANDS {
            get {
                return ResourceManager.GetString("CT_CONFIGCOMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a dataTypes.
        /// </summary>
        public static string CT_DATATYPES {
            get {
                return ResourceManager.GetString("CT_DATATYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a datetimeFunctions.
        /// </summary>
        public static string CT_DATETIMEFUNC {
            get {
                return ResourceManager.GetString("CT_DATETIMEFUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DMLCommands.
        /// </summary>
        public static string CT_DMLCOMMANDS {
            get {
                return ResourceManager.GetString("CT_DMLCOMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DMLTokens.
        /// </summary>
        public static string CT_DMLTOKENS {
            get {
                return ResourceManager.GetString("CT_DMLTOKENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EnumConstants.
        /// </summary>
        public static string CT_ENUMCONSTANTS {
            get {
                return ResourceManager.GetString("CT_ENUMCONSTANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EnumProperties.
        /// </summary>
        public static string CT_ENUMPROPERTIES {
            get {
                return ResourceManager.GetString("CT_ENUMPROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FIlterCommand.
        /// </summary>
        public static string CT_FILTERCOMMANDS {
            get {
                return ResourceManager.GetString("CT_FILTERCOMMANDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a intervalNames.
        /// </summary>
        public static string CT_INTERVALNAME {
            get {
                return ResourceManager.GetString("CT_INTERVALNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IntProperties.
        /// </summary>
        public static string CT_INTPROPERTIES {
            get {
                return ResourceManager.GetString("CT_INTPROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tableJoins.
        /// </summary>
        public static string CT_JOINS {
            get {
                return ResourceManager.GetString("CT_JOINS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a literalTokens.
        /// </summary>
        public static string CT_LITERALTOKENS {
            get {
                return ResourceManager.GetString("CT_LITERALTOKENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a logicOperators.
        /// </summary>
        public static string CT_LOGICOPERATORS {
            get {
                return ResourceManager.GetString("CT_LOGICOPERATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LogicPseudoOperators.
        /// </summary>
        public static string CT_LOGICPSEUDOOPERATORS {
            get {
                return ResourceManager.GetString("CT_LOGICPSEUDOOPERATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a multiTypeFunctions.
        /// </summary>
        public static string CT_MTFUNCTIONS {
            get {
                return ResourceManager.GetString("CT_MTFUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a numberFunctions.
        /// </summary>
        public static string CT_NUMBERFUNC {
            get {
                return ResourceManager.GetString("CT_NUMBERFUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One-ArgumentDateTimeFunctions.
        /// </summary>
        public static string CT_OADTFUNCTIONS {
            get {
                return ResourceManager.GetString("CT_OADTFUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One-ArgumentNumberFunctions.
        /// </summary>
        public static string CT_OANUMBERFUNC {
            get {
                return ResourceManager.GetString("CT_OANUMBERFUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One-ArgumentStringFunctions.
        /// </summary>
        public static string CT_OASTRFUNCTIONS {
            get {
                return ResourceManager.GetString("CT_OASTRFUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ParaneterConfiguration.
        /// </summary>
        public static string CT_PARAMCONFIGURATION {
            get {
                return ResourceManager.GetString("CT_PARAMCONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a reservedWords.
        /// </summary>
        public static string CT_RESERVEDWORDS {
            get {
                return ResourceManager.GetString("CT_RESERVEDWORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a selVariants.
        /// </summary>
        public static string CT_SELECTTOKENS {
            get {
                return ResourceManager.GetString("CT_SELECTTOKENS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a setJoinOperators.
        /// </summary>
        public static string CT_SETJOINOPERATORS {
            get {
                return ResourceManager.GetString("CT_SETJOINOPERATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a setOperators.
        /// </summary>
        public static string CT_SETOPERATORS {
            get {
                return ResourceManager.GetString("CT_SETOPERATORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a specialTokens.
        /// </summary>
        public static string CT_SPECIAL {
            get {
                return ResourceManager.GetString("CT_SPECIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a stringFunctions.
        /// </summary>
        public static string CT_STRINGFUNC {
            get {
                return ResourceManager.GetString("CT_STRINGFUNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StringProperties.
        /// </summary>
        public static string CT_STRINGPROPERTIES {
            get {
                return ResourceManager.GetString("CT_STRINGPROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a symbols.
        /// </summary>
        public static string CT_SYMBOLS {
            get {
                return ResourceManager.GetString("CT_SYMBOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a timeStampFunctions.
        /// </summary>
        public static string CT_TSFUNCTIONS {
            get {
                return ResourceManager.GetString("CT_TSFUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a unknownReturnTypeFunctions.
        /// </summary>
        public static string CT_URTFUNCTIONS {
            get {
                return ResourceManager.GetString("CT_URTFUNCTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ....
        /// </summary>
        public static string CTK_SUGGESTION {
            get {
                return ResourceManager.GetString("CTK_SUGGESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checkbox.
        /// </summary>
        public static string EDIT_CheckBox {
            get {
                return ResourceManager.GetString("EDIT_CheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date.
        /// </summary>
        public static string EDIT_Date {
            get {
                return ResourceManager.GetString("EDIT_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Date Interval.
        /// </summary>
        public static string EDIT_DateInterval {
            get {
                return ResourceManager.GetString("EDIT_DateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DateTime.
        /// </summary>
        public static string EDIT_DateTime {
            get {
                return ResourceManager.GetString("EDIT_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DateTime INterval.
        /// </summary>
        public static string EDIT_DateTimeInterval {
            get {
                return ResourceManager.GetString("EDIT_DateTimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EnumCB.
        /// </summary>
        public static string EDIT_Enum {
            get {
                return ResourceManager.GetString("EDIT_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Float List.
        /// </summary>
        public static string EDIT_FList {
            get {
                return ResourceManager.GetString("EDIT_FList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Float.
        /// </summary>
        public static string EDIT_Float {
            get {
                return ResourceManager.GetString("EDIT_Float", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integer List.
        /// </summary>
        public static string EDIT_IList {
            get {
                return ResourceManager.GetString("EDIT_IList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integer.
        /// </summary>
        public static string EDIT_Int {
            get {
                return ResourceManager.GetString("EDIT_Int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interval.
        /// </summary>
        public static string EDIT_Interval {
            get {
                return ResourceManager.GetString("EDIT_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List.
        /// </summary>
        public static string EDIT_List {
            get {
                return ResourceManager.GetString("EDIT_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logic.
        /// </summary>
        public static string EDIT_Logic {
            get {
                return ResourceManager.GetString("EDIT_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multiline Text.
        /// </summary>
        public static string EDIT_MLText {
            get {
                return ResourceManager.GetString("EDIT_MLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        public static string EDIT_None {
            get {
                return ResourceManager.GetString("EDIT_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a String List.
        /// </summary>
        public static string EDIT_SList {
            get {
                return ResourceManager.GetString("EDIT_SList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Triestate Logic.
        /// </summary>
        public static string EDIT_TELogic {
            get {
                return ResourceManager.GetString("EDIT_TELogic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text.
        /// </summary>
        public static string EDIT_Text {
            get {
                return ResourceManager.GetString("EDIT_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time.
        /// </summary>
        public static string EDIT_Time {
            get {
                return ResourceManager.GetString("EDIT_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time Interval.
        /// </summary>
        public static string EDIT_TimeInterval {
            get {
                return ResourceManager.GetString("EDIT_TimeInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CQC.
        /// </summary>
        public static string ID_CommandQueryColumn {
            get {
                return ResourceManager.GetString("ID_CommandQueryColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a defaultconnection.
        /// </summary>
        public static string ID_CSDefault {
            get {
                return ResourceManager.GetString("ID_CSDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a exportconnection.
        /// </summary>
        public static string ID_CSExportClass {
            get {
                return ResourceManager.GetString("ID_CSExportClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDCONNCLASS.
        /// </summary>
        public static string ID_CStringClass {
            get {
                return ResourceManager.GetString("ID_CStringClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DefaultQueries.
        /// </summary>
        public static string ID_DefaultQueries {
            get {
                return ResourceManager.GetString("ID_DefaultQueries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a InteractiveColumnType.
        /// </summary>
        public static string ID_ExtColPropertyICType {
            get {
                return ResourceManager.GetString("ID_ExtColPropertyICType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDGCODE.
        /// </summary>
        public static string ID_GroupCode {
            get {
                return ResourceManager.GetString("ID_GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDPARNAME.
        /// </summary>
        public static string ID_ParameterName {
            get {
                return ResourceManager.GetString("ID_ParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDPARPATH.
        /// </summary>
        public static string ID_ParameterPath {
            get {
                return ResourceManager.GetString("ID_ParameterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QC.
        /// </summary>
        public static string ID_QueryColumn {
            get {
                return ResourceManager.GetString("ID_QueryColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QCP.
        /// </summary>
        public static string ID_QueryCommandParameter {
            get {
                return ResourceManager.GetString("ID_QueryCommandParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QP.
        /// </summary>
        public static string ID_QueryParameter {
            get {
                return ResourceManager.GetString("ID_QueryParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IDUCODE.
        /// </summary>
        public static string ID_UserCode {
            get {
                return ResourceManager.GetString("ID_UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;TextContainer xmlns=&quot;http://schemas.datacontract.org/2004/07/BaseClassesAndInterfaces.Serialization&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;Text xmlns:a=&quot;http://schemas.microsoft.com/2003/10/Serialization/Arrays&quot;&gt;
        ///    &lt;a:string&gt;with tree as&lt;/a:string&gt;
        ///    &lt;a:string&gt;(select cod_group,convert(varchar(1000),grp_name) gname,cod_parent from cfg_groups &lt;/a:string&gt;
        ///    &lt;a:string&gt;where cod_parent is null&lt;/a:string&gt;
        ///    &lt;a:string&gt;union all&lt;/a:string&gt;
        ///    &lt;a:string&gt;select g.cod_group,convert(v [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string loginquery {
            get {
                return ResourceManager.GetString("loginquery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table.
        /// </summary>
        public static string OBJTYPE_TABLE {
            get {
                return ResourceManager.GetString("OBJTYPE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        public static string OBJTYPE_VIEW {
            get {
                return ResourceManager.GetString("OBJTYPE_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;SerializableQueryConfiguration xmlns=&quot;http://schemas.datacontract.org/2004/07/BaseClassesAndInterfaces.Serialization&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;ColumnUIDs xmlns:a=&quot;http://schemas.datacontract.org/2004/07/BaseClassesAndInterfaces.Application&quot;&gt;&lt;a:SerializableUID&gt;&lt;a:ObjectID&gt;cod_parameter&lt;/a:ObjectID&gt;&lt;a:UID&gt;df09d9073c9145f9bfaeb240f0c172b2&lt;/a:UID&gt;&lt;/a:SerializableUID&gt;&lt;a:SerializableUID&gt;&lt;a:ObjectID&gt;section&lt;/a:ObjectID&gt;&lt;a:UID&gt;f7caabfc03a74803a89c2ddb1f8dcc1e&lt;/a:UID&gt;&lt;/a:SerializableUID&gt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string parameters {
            get {
                return ResourceManager.GetString("parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _CONNQ.
        /// </summary>
        public static string POST_ConnecionQuery {
            get {
                return ResourceManager.GetString("POST_ConnecionQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _PARAMQ.
        /// </summary>
        public static string POST_ParameterQuery {
            get {
                return ResourceManager.GetString("POST_ParameterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a APP_.
        /// </summary>
        public static string PRE_APP {
            get {
                return ResourceManager.GetString("PRE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DESCR_.
        /// </summary>
        public static string PRE_DESCR {
            get {
                return ResourceManager.GetString("PRE_DESCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ENUM_.
        /// </summary>
        public static string PRE_ENUM {
            get {
                return ResourceManager.GetString("PRE_ENUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NAME_.
        /// </summary>
        public static string PRE_NAME {
            get {
                return ResourceManager.GetString("PRE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a connection.
        /// </summary>
        public static string SBSTR_CONN {
            get {
                return ResourceManager.GetString("SBSTR_CONN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a connections.
        /// </summary>
        public static string SBSTR_CONNS {
            get {
                return ResourceManager.GetString("SBSTR_CONNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a file.
        /// </summary>
        public static string SBSTR_FILE {
            get {
                return ResourceManager.GetString("SBSTR_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a login.
        /// </summary>
        public static string SBSTR_LOGIN {
            get {
                return ResourceManager.GetString("SBSTR_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a parameters.
        /// </summary>
        public static string SBSTR_PARAM {
            get {
                return ResourceManager.GetString("SBSTR_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a resource.
        /// </summary>
        public static string SBSTR_RESX {
            get {
                return ResourceManager.GetString("SBSTR_RESX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a serializer.
        /// </summary>
        public static string SBSTR_SER {
            get {
                return ResourceManager.GetString("SBSTR_SER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a type.
        /// </summary>
        public static string SBSTR_TYPE {
            get {
                return ResourceManager.GetString("SBSTR_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xml.
        /// </summary>
        public static string SBSTR_XML {
            get {
                return ResourceManager.GetString("SBSTR_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;SerializableQueryConfiguration xmlns=&quot;http://schemas.datacontract.org/2004/07/BaseClassesAndInterfaces.Serialization&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;&lt;ColumnConfiguration&gt;&lt;SerializableColumnConfiguration&gt;&lt;ElementID&gt;xmlobject_name&lt;/ElementID&gt;&lt;ElementType&gt;BaseClassesAndInterfaces.SQL.QueryColumn&lt;/ElementType&gt;&lt;FriendlyDescription i:nil=&quot;true&quot;/&gt;&lt;FriendlyName i:nil=&quot;true&quot;/&gt;&lt;Interactive&gt;false&lt;/Interactive&gt;&lt;UICategory i:nil=&quot;true&quot;/&gt;&lt;Caption&gt;Name&lt;/Caption&gt;&lt;ColumnType&gt;None&lt;/ColumnType&gt;&lt;Descripti [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string selxmlobjects {
            get {
                return ResourceManager.GetString("selxmlobjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a binaryArray.
        /// </summary>
        public static string TK_BINARYARRAY {
            get {
                return ResourceManager.GetString("TK_BINARYARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a decimalNumber.
        /// </summary>
        public static string TK_DECNUMBERS {
            get {
                return ResourceManager.GetString("TK_DECNUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 6A00CE81-6727-4323-90D9-DE242B2A91B2.
        /// </summary>
        public static string UID_BooleanParamEditor {
            get {
                return ResourceManager.GetString("UID_BooleanParamEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1649A84F-4AAF-4332-81E3-C423D40A8427.
        /// </summary>
        public static string UID_ComboBoxEditableParamEditor {
            get {
                return ResourceManager.GetString("UID_ComboBoxEditableParamEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 77D4B3DC-83F4-445C-9E9A-833646DF5CE9.
        /// </summary>
        public static string UID_ComboBoxParamEditor {
            get {
                return ResourceManager.GetString("UID_ComboBoxParamEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 90CF0196-0C68-4671-8985-DABADA07F2E0.
        /// </summary>
        public static string UID_DBProviderList {
            get {
                return ResourceManager.GetString("UID_DBProviderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 020B34E2-36FA-4EF1-B9E8-2375DF0C3C3D.
        /// </summary>
        public static string UID_DTPDateandTimeEditor {
            get {
                return ResourceManager.GetString("UID_DTPDateandTimeEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AC805510-7238-4373-B11B-2E9FCB9EB053.
        /// </summary>
        public static string UID_DTPDateEditor {
            get {
                return ResourceManager.GetString("UID_DTPDateEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B0ACF2F6-ACD7-49A9-8973-2A44E45D7CD1.
        /// </summary>
        public static string UID_EmailParameterEditor {
            get {
                return ResourceManager.GetString("UID_EmailParameterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 07798652-CF66-4653-BBEE-B604705052B8.
        /// </summary>
        public static string UID_GUIDGenerator {
            get {
                return ResourceManager.GetString("UID_GUIDGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 86E52F57-621D-4C24-A409-B2B1069ED09D.
        /// </summary>
        public static string UID_ModalFileParameterEditor {
            get {
                return ResourceManager.GetString("UID_ModalFileParameterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1801C55C-EB0F-4520-81D0-5E360B1C2FBE.
        /// </summary>
        public static string UID_ModalPathParameterEditor {
            get {
                return ResourceManager.GetString("UID_ModalPathParameterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 528DF98F-5030-4C34-B483-FB370841FA63.
        /// </summary>
        public static string UID_MultiValuedParameterEditor {
            get {
                return ResourceManager.GetString("UID_MultiValuedParameterEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 76786711-BD59-42E1-BBCA-9BCB263EC791.
        /// </summary>
        public static string UID_SimpleTextParamEditor {
            get {
                return ResourceManager.GetString("UID_SimpleTextParamEditor", resourceCulture);
            }
        }
    }
}
